# Generated by Django 3.0.1 on 2020-01-04 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoqaStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(blank=True, max_length=100)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CoqaStory')),
            ],
        ),
    ]
